---
functional:

  - У сайта должен быть механизм регистрации нового пользователя по email адресу и учетным записям Github/Discord
  - У сайта должен быть механизм авторизации пользователя по email адресу и учетным записям Github/Discord
  - У сайта должен быть механизм восстановления  учетной записи
  - Главная страница сайта должна содержать основную информацию о продукте с заголовком, кратким описанием, изображением и пр.
  - Сайт должен иметь функционал создания игры в разных режимах игра с ботом, игра с другом, игра с другим пользователем
  - У пользователей должен быть реализован индивидуальный рейтинг по результату игр
  - Следует вести статистику лучших игроков за период времени
  - На сайте должен отображаться онлайн игроков
  - Должна быть отображена история пройденных игр
  - Пользователь должен иметь возможность создать игровую комнату
  - Необходимо разработать меню сайта с такими характеристиками Профиль пользователя, Настройки, Рейтинг игроков, Упражнения, Таблица турниров
  - Профиль пользователя должен состоять из Аватара, Имени пользователя, Личной статистики, Языка программирования, Наград, Даты регистрации, Завершенных игр
  - Пользователи должны иметь возможность устраивать соревновательные турниры с другими игроками
  - Незарегистрированный пользователь должен иметь возможность открывать игровую комнату
  - Должна быть реализована возможность общения между игроками
  - У сайта должно быть разработано расширение для браузера
  - Пользователи должны иметь возможность присоединится к текущей игре
  - Пользователи должен иметь возомжность взаимодействовать с другими игроками
  - Должна быть реализована функция вызова краткой характеристики пользовател
  - Все поля и формы должны проходить валидацию
  - Бот в активной игре должен написать код до истечения времени
  
non-functional:
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь адаптивную верстку
  - Сайт должен быть безопасным и защищать данные пользователя
  
implicit:
  - Нет оповещения о регистрации на почту
