---
functional:
  - У сайта должен быть механизм регистрации нового пользователя по email адресу и учетным записям Github/Discord
  - У сайта должен быть механизм авторизации пользователя по email адресу и учетным записям Github/Discord
  - У сайта должен быть механизм восстановления  учетной записи
  - Главная страница сайта должна содержать основную информацию о продукте с заголовком, кратким описанием, изображением и пр.
  - Сайт должен иметь функционал создания игры в разных режимах: игра с ботом, игра с другом, игра с другим пользователем
  - При создании игры необходимо реализовать функционал настройки игры: сложность, ограничение по времени, выбор задания
  - Пользователи должны иметь возможность общаться друг с другом в общем чате
  - У пользователей должен быть реализован индивидуальный рейтинг по результату игр
  - Следует ввести в виде таблицы статистику лучших игроков за период времени: неделя, месяц
  - На сайте должен отображаться онлайн игроков
  - На сайте должно быть отображение текущих игр
  - Пользователи должны иметь возможность добавлять новые задания для прохождения другими участиниками
  - Должна быть отображена история пройденных игр
  - Пользователь должен иметь возможность создать игровую комнату
  - Необходимо разработать меню сайта с такими характеристиками: Профиль пользователя, Настройки, Рейтинг игроков, Упражнения, Таблица турниров
  - Профиль пользователя должен состоять из Аватара, Имени пользователя, Личная статистики, Предпочитаемого языка программирования, Даты регистрации, Таблицы завершенных игр
  - Пользователи должны иметь возможность устраивать соревновательные турниры с другими игроками
  - Незарегистрированный пользователь должен иметь возможность открывать игровую комнату
  - Должна быть реализована возможность общения между игроками
  - Пользователи должны иметь возможность создавать игровые комнаты с другими игроками
  
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь адаптивную верстку
  - Сайт интернет-магазина должен быть SPA-приложением
  - Соединение с сайтом должно осуществляться по HTTPS соединению
  - Сертификат SSL/TLS сайта должен быть действительным 
  
implicit:
  - Нет оповещения о регистрации на почту
  - 
  
  
